# Generated by Django 5.0.6 on 2024-07-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
