# Generated by Django 5.0.6 on 2024-07-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_password_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='religiousevent',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
